### ISSUE TITLE
stimulus new version 3.0 is not compatible

### ISSUE THREAD

**Issue by jicheng1014** [stimulus-components/stimulus-popover#12] opened 2021-11-15 16:46 UTC
`import { Controller } from 'stimulus'`  doesn't work when user install stimulus from `@hotwired/stimulus`

**Comment by Sybio** [comment] 2021-12-28 11:24
Same here

**Comment by guillaumebriday** [comment] 2021-12-28 13:02
I would like to fix a bug at this line https://github.com/stimulus-components/stimulus-popover/blob/master/src/index.ts#L30 with the `currentTarget` vs `target` before release a new version with Stimulus 3

**Comment by AlexKovynev** [comment] 2022-05-11 03:16
@guillaumebriday Maybe it is time to release version for stimulus 3?:)

**Comment by ChechkovEugene** [comment] 2022-05-12 13:59
The same. Voting for stimulus 3 :)

**Comment by kluzny** [comment] 2022-07-12 16:08
@guillaumebriday Would you be willing to outline the bug in a test or an issue? Its not obvious to me what the problem is and if it is holding up https://github.com/stimulus-components/stimulus-popover/pull/14 it would be nice to finally advance support to hotwire.

**Comment by guillaumebriday** [comment] 2022-08-12 11:25
Released in https://github.com/stimulus-components/stimulus-popover/releases/tag/v6.0.0

And the `currentTarget` has been fixed in https://github.com/stimulus-components/stimulus-popover/releases/tag/v6.1.0

Enjoy! 🎉

**Closed by guillaumebriday** 2022-08-12 11:25 UTC
